# Generated by Django 5.1 on 2025-06-25 03:37

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consultancy",
            name="contact",
        ),
        migrations.AddField(
            model_name="consultancy",
            name="address",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=100,
                verbose_name="Office Address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultancy",
            name="mobile_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
        migrations.AddField(
            model_name="consultancy",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?\\d{7,15}$",
                    )
                ],
                verbose_name="Phone Number (Landline)",
            ),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="cons_name",
            field=models.CharField(max_length=50, verbose_name="Consultancy Name"),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="content",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="consultancy"),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Email Address"),
        ),
    ]
