# Generated by Django 5.1 on 2025-06-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_remove_consultancy_contact_consultancy_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultancy",
            name="mobile_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mobile Number"
            ),
        ),
        migrations.AlterField(
            model_name="consultancy",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Phone Number (Landline)",
            ),
        ),
    ]
