# Generated by Django 5.1 on 2025-06-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_consultancy_mobile_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="gallery")),
                ("image_name", models.TextField()),
            ],
        ),
    ]
