# Generated by Django 5.0.4 on 2025-07-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_course_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "link",
                    models.URLField(help_text="Paste Google Docs/Sheets link here"),
                ),
            ],
        ),
    ]
