# Generated by Django 5.0.4 on 2025-07-16 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_mocktest"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultancy",
            name="why_to_choose",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="Why To Choose"
            ),
            preserve_default=False,
        ),
    ]
